cc_library(
    name = "widgets",
    hdrs = glob(["*.h"]),
    srcs = glob(["*.cc"]),
    visibility = ["//src/framework:__subpackages__", "//tests:__subpackages__"],
    deps = [
        "@native_ui//src/framework/core",
        "@native_ui//src/framework/layout",
        "@native_ui//src/framework/render",
        "@native_ui//src/framework/state",
        "@yoga//:yoga",
    ],
)
