cc_library(
    name = "widgets",
    hdrs = glob(["*.h"]),
    srcs = glob(["*.cc"]),
    includes = ["."],
    visibility = ["//src/framework:__subpackages__", "//tests:__subpackages__"],
    deps = [
        "//src/framework/core",
        "//src/framework/layout",
        "//src/framework/render",
        "//src/framework/viewmodel",
        "@yoga//:yoga",
    ],
)
