cc_library(
    name = "render",
    hdrs = glob(["*.h"]),
    srcs = glob(["*.cc"]),
    includes = ["."],
    visibility = ["//src/framework:__subpackages__", "//tests:__subpackages__", "//examples:__subpackages__"],
    deps = [
        "//src/framework/core",
        "//src/framework/surface",
        "//third_party/stblib:stb_image",
        "@nanosvg//:nanosvg",
        "@skia//:skia",
    ],
)
