cc_library(
    name = "render",
    hdrs = glob(["*.h"]),
    srcs = glob(["*.cc"]),
    includes = ["."],
    visibility = ["//src/framework:__subpackages__", "//tests:__subpackages__"],
    deps = [
        "//src/framework/core",
        "//src/framework/surface",
        "@skia//:skia",
    ],
)
