package(default_visibility = ["//src/spike:__subpackages__"])

cc_binary(
    name = "skia_spike",
    srcs = ["skia_spike.cc"],
    deps = ["//src/framework/utils"],
)

cc_binary(
    name = "yoga_spike",
    srcs = ["yoga_spike.cc"],
    deps = [
        "//src/framework/utils",
        "@yoga//:yoga",
    ],
)
