cc_test(
    name = "infra_test",
    srcs = ["infra_test.cc"],
    deps = ["@com_google_googletest//:gtest_main"],
)

cc_test(
    name = "core_rect_test",
    srcs = ["core_rect_test.cc"],
    deps = [
        "//src/framework/core",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "core_point_test",
    srcs = ["core_point_test.cc"],
    deps = [
        "//src/framework/core",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "core_type_test",
    srcs = ["core_type_test.cc"],
    deps = [
        "//src/framework/core",
        "@com_google_googletest//:gtest_main",
    ],
)
