cc_test(
    name = "infra_test",
    srcs = ["infra_test.cc"],
    deps = ["@com_google_googletest//:gtest_main"],
)

cc_test(
    name = "core_rect_test",
    srcs = ["core_rect_test.cc"],
    deps = [
        "@native_ui//src/framework/core",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "core_point_test",
    srcs = ["core_point_test.cc"],
    deps = [
        "@native_ui//src/framework/core",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "core_type_test",
    srcs = ["core_type_test.cc"],
    deps = [
        "@native_ui//src/framework/core",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "property_test",
    srcs = ["property_test.cc"],
    deps = [
        "@native_ui//src/framework/state",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "state_test",
    srcs = ["state_test.cc"],
    deps = [
        "@native_ui//src/framework/widgets",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "widget_test",
    srcs = ["widget_test.cc"],
    deps = [
        "@native_ui//src/framework/widgets",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "container_test",
    srcs = ["container_test.cc"],
    deps = [
        "@native_ui//src/framework/widgets",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "layout_test",
    srcs = ["layout_test.cc"],
    deps = [
        "@native_ui//src/framework/layout",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "render_test",
    srcs = ["render_test.cc"],
    deps = [
        "@native_ui//src/framework/render",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "surface_test",
    srcs = ["surface_test.cc"],
    deps = [
        "@native_ui//src/framework/surface",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "external_image_test",
    srcs = ["external_image_test.cc"],
    deps = [
        "@native_ui//src/framework/widgets",
        "@native_ui//src/framework/render",
        "@native_ui//src/framework/surface",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "widgets_test",
    srcs = ["widgets_test.cc"],
    deps = [
        "@native_ui//src/framework/widgets",
        "@native_ui//src/framework/render",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "event_test",
    srcs = ["event_test.cc"],
    deps = [
        "@native_ui//src/framework/event",
        "@native_ui//src/framework/widgets",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "debug_overlay_test",
    srcs = ["debug_overlay_test.cc"],
    deps = [
        "@native_ui//src/framework/widgets",
        "@native_ui//src/framework/render",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "examples_test",
    srcs = ["examples_test.cc"],
    deps = [
        "@native_ui//src/framework/widgets",
        "@native_ui//src/framework/render",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "style_test",
    srcs = ["style_test.cc"],
    deps = [
        "@native_ui//src/framework/widgets",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "glide_test",
    srcs = ["glide_test.cc"],
    deps = [
        "@native_ui//src/framework/widgets",
        "@com_google_googletest//:gtest_main",
    ],
)
