cc_binary(
    name = "hello_world",
    srcs = ["hello_world.cc"],
    deps = [
        "@native_ui//src/framework/public:native_ui",
        "@native_ui//src/framework/surface",
        "@native_ui//src/framework/utils",
        "@skia//:skia",
    ],
)

cc_binary(
    name = "image_gallery",
    srcs = ["image_gallery.cc"],
    data = [
        "@native_ui//assets/photo:photos",
    ],
    deps = [
        "@native_ui//src/framework/public:native_ui",
        "@native_ui//src/framework/surface",
        "@native_ui//src/framework/utils",
        "@skia//:skia",
    ],
)
