cc_library(
    name = "native_ui",
    hdrs = glob(["include/native_ui/*.h"]),
    strip_include_prefix = "include",
    copts = [
        "-fvisibility=hidden",
        "-fvisibility-inlines-hidden",
        "-DNATIVE_UI_SHARED_LIBRARY",
    ],
    alwayslink = 1,
    deps = [
        "@native_ui//src/framework/core",
        "@native_ui//src/framework/layout",
        "@native_ui//src/framework/render",
        "@native_ui//src/framework/surface",
        "@native_ui//src/framework/state",
        "@native_ui//src/framework/widgets",
        "@native_ui//src/framework/event",
    ],
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "native_ui_shared",
    linkshared = True,
    deps = [":native_ui"],
)
