cc_library(
    name = "surface",
    hdrs = glob(["*.h"]),
    srcs = glob(["*.cc"]),
    visibility = ["//src/framework:__subpackages__", "//tests:__subpackages__", "//examples:__subpackages__"],
    deps = [
        "@native_ui//src/framework/core",
        "@skia//:skia",
        "@stblib//:stb_image_write",
    ] + select({
        "@native_ui//platforms:android_arm64": ["@skia//:skia_gpu"],
        "//conditions:default": [],
    }),
    linkopts = select({
        "@native_ui//platforms:android_arm64": [
            "-landroid",
            "-llog",
        ],
        "//conditions:default": [],
    }),
)
